BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part
FLAG_ROWS = 3
FLAG_COLS = 4
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

GREEN = (0, 51, 0)

LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
LOSE_COLOR=WIN_COLOR
FONT_NAME = "Calibri"

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3
EMPTY=""
MINE=1